### ISSUE TITLE
Slides for Week 2

### ISSUE THREAD

**Issue by hprop** [mcv-m6-video/class2018#2]
Hi!

Could you please upload the slides for Week 2? In the campus virtual we have a link to the slides of the previous course 16/17, but some material have changed for this year (eg. Task 3).

Thank you!

Team 9

**Comment by xavigiro** [comment]
Yes, [here](https://docs.google.com/presentation/d/18k5I_qsz7qcBfOP4SnM8Y1xjTgQwwfHrQ8q_5lEjYUU/edit?usp=sharing) you have them.
