### ISSUE TITLE
Intragroup evaluation Week 3

### ISSUE THREAD

**Issue by MrLeylo** [mcv-m6-video/class2018#5]
Hi, we have just found that the link provided in Week 3 preslides for intragroup evaluation goes to a closed form. How could we deliver it to you?

Thank you.

**Comment by xavigiro** [comment]
Hi @MrLeylo ,

that was my mistake when linking from the [slides](https://docs.google.com/presentation/d/1TsiHmW41oVaRd_tMT9Fy_S71ccx9HAqIOa6N9hYYIfY/edit?usp=sharing). The correct links is now fixed, and you can also access this form [here](https://docs.google.com/forms/d/e/1FAIpQLSe7ySHMh_05LlvALXMVbXqgWJw_1-kUnlnGce8y487s7cCLgQ/viewform?usp=sf_link).

Please have it submitted before Monday 26th March 2018 at 9am.
